# app/Dockerfile

# This contianer will seed our elasticsearch db running in our cluster.

FROM python:3.9-slim
WORKDIR /app
COPY data/ ./data
COPY requirements.txt . 
COPY ingest_data.py	 .

RUN pip3 install -r requirements.txt
CMD [ "python", "ingest_data.py", "ES_HOSTNAME" ] 

